vtex/profile-form

- LICENSE
- package.json
> Add AGPL 3.0 LICENSE 

- CHANGELOG.md
- manifest.json
- package.json
- react/ProfileRules.js
Fix fallback of rule loading.
Try to use a profile from a country that doesn't have a rule.
n/a
> Fix rules loading

- CHANGELOG.md
- README.md
- manifest.json
- package.json
> Updates version

- CHANGELOG.md
- jest.transform.js
- manifest.json
- package.json
- react/ProfileRules.js
- react/__tests__/ProfileRules.test.js
- react/rules/ARG.js
- react/rules/BRA.js
- react/rules/CAN.js
- react/rules/CHL.js
- react/rules/COL.js
- react/rules/CRI.js
- react/rules/ECU.js
- react/rules/ESP.js
- react/rules/FRA.js
- react/rules/GBR.js
- react/rules/GTM.js
- react/rules/KOR.js
- react/rules/MEX.js
- react/rules/PAN.js
- react/rules/PER.js
- react/rules/PRT.js
- react/rules/PRY.js
- react/rules/ROU.js
- react/rules/URY.js
- react/rules/USA.js
- react/rules/VEN.js
- react/rules/default.js
- yarn.lock
- Insert default functions to rules of type date
> Insert default functions to rules of type date

- CHANGELOG.md
- manifest.json
- package.json
> Release v2.4.2

- CHANGELOG.md
- manifest.json
- package.json
> Release v2.4.3

- CHANGELOG.md
- manifest.json
- package.json
- react/rules/ESP.js
> Changed the obligation of document on spain.

- CHANGELOG.md
- manifest.json
- package.json
- react/rules/ARG.js
- react/rules/BRA.js
- react/rules/CAN.js
- react/rules/CHL.js
- react/rules/COL.js
- react/rules/CRI.js
- react/rules/ECU.js
- react/rules/ESP.js
- react/rules/FRA.js
- react/rules/GBR.js
- react/rules/GTM.js
- react/rules/KOR.js
- react/rules/MEX.js
- react/rules/PAN.js
- react/rules/PER.js
- react/rules/PRT.js
- react/rules/PRY.js
- react/rules/URY.js
- react/rules/USA.js
- react/rules/VEN.js
- react/rules/initializeCountryPhone.js
> Fix `@vtex/phone` initialization

- CHANGELOG.md
- manifest.json
- react/ProfileContainer.js
- react/ProfileSummary.js
- react/inputs/StyleguideInput/AutocompleteInput.js
- react/inputs/StyleguideInput/AutocompleteMenu.js
- react/inputs/StyleguideInput/GenderInput.js
- react/inputs/StyleguideInput/index.js
Make the application more customizable
You can't customize  some elements of the app, like change the order of things
Access this [workspce](https://klynger--storecomponents.myvtex.com/admin/customers) and click the button `NOVO`.
> Add css tokens to all HTML elements of all components

- CHANGELOG.md
- package.json
- react/ProfileRules.js
- react/modules/removeValidation.js
- react/yarn.lock
- yarn.lock
> Revert "Fix/birth date decrementing"

- CHANGELOG.md
- manifest.json
- package.json
- react/ProfileRules.js
- react/modules/removeValidation.js
- react/yarn.lock
- yarn.lock
Restore vtex/profile-form#36 with app published
> Revert "Revert "Fix/birth date decrementing""

- CHANGELOG.md
- manifest.json
- react/ProfileContainer.js
- react/ProfileSummary.js
- react/inputs/StyleguideInput/AutocompleteInput.js
- react/inputs/StyleguideInput/AutocompleteMenu.js
- react/inputs/StyleguideInput/GenderInput.js
- react/inputs/StyleguideInput/index.js
This reverts commit 5dc466343893ca3d274b552b945c273896349b0e.
> Revert "Add tokens to elements of all components"

- CHANGELOG.md
- manifest.json
- react/ProfileContainer.js
- react/ProfileSummary.js
- react/inputs/StyleguideInput/AutocompleteInput.js
- react/inputs/StyleguideInput/AutocompleteMenu.js
- react/inputs/StyleguideInput/GenderInput.js
- react/inputs/StyleguideInput/index.js
Add CSS tokens to elements
Access the [worksapce](https://profileformtokens--recorrenciaqa.myvtex.com/account#/profile/edit) and see the tokens in the elements
> Add css tokens

- CHANGELOG.md
- manifest.json
- react/ProfileContainer.js
- react/ProfileSummary.js
- react/inputs/StyleguideInput/AutocompleteInput.js
- react/inputs/StyleguideInput/AutocompleteMenu.js
- react/inputs/StyleguideInput/GenderInput.js
- react/inputs/StyleguideInput/index.js
- react/styles.css
Add css handles to elements
Access the [workspace](https://cssmodulesform--storecomponents.myvtex.com/admin/customers) and click in `NEW` to open the form
I didn't remove some css tokens that were already there in order to not break anyone
> Create css handles

- CHANGELOG.md
- manifest.json
- package.json
- react/rules/COL.js
Title is self-explanatory.
The regex validator for COL was incorrect.
> Fix document validation regex

- CHANGELOG.md
- manifest.json
- package.json
- react/ProfileContainer.js
- react/__tests__/ProfileContainer.test.js
> Fixed submit on enter 

- CHANGELOG.md
- manifest.json
- messages/pt-PT.json
- package.json
Title is self-explanatory.
We need specific translations for portugal's portuguese.
> Add pt-PT.json

- CHANGELOG.md
- manifest.json
- messages/pt-PT.json
- package.json
> Feature/add pt pt 3.x

- .eslintignore
- .eslintrc
- .prettierrc
- CHANGELOG.md
- package.json
- react/.eslintrc
- react/package.json
- react/tsconfig.json
- react/yarn.lock
- yarn.lock
Run `vtex setup`
Deploy version 2.7.1 since 2.7.0 had already been published on IO.
> Run vtex setup

- CHANGELOG.md
- react/rules/ITA.js
- ditto.
- Italian stores don't require document.
- https://vtex-dev.atlassian.net/secure/RapidBoard.jspa?rapidView=109&modal=detail&selectedIssue=POST-673
- Same as: https://github.com/vtex/profile-form/pull/91
- https://felipe--arcaplanet.myvtex.com/account?__inspect#/profile/edit
> Added specific rules for ITA

- CHANGELOG.md
- react/rules/ITA.js
- ditto.
- Italian stores don't require document.
- https://vtex-dev.atlassian.net/secure/RapidBoard.jspa?rapidView=109&modal=detail&selectedIssue=POST-673
- https://felipe--arcaplanet.myvtex.com/account?__inspect#/profile/edit
> [3.x] Added specific rules for ITA

- CHANGELOG.md
- manifest.json
- ditto.
- Dunno why there were some versions released for this app, but they were not present on this repo.
As you can see this:
- impersonate: `assinaturasqa@mailinator.com`
- https://recorrenciacharlie.vtexcommercestable.com.br/_secure/account?workspace=cabaceiras#/profile?success=true
> Fix release

- CHANGELOG.md
- react/rules/RUS.js
We are adding the configuration for Russia.
Solve a problem with Date of Birthday, now you can save. Also, we add a mask like in ROU.
We test it by linking the APP to a workspace.
> Adding RUS Profile for v3.x

- CHANGELOG.md
- react/rules/RUS.js
We are adding the configuration for Russia.
Solve a problem with Date of Birthday, now you can save. Also we add a mask like in ROU.
We test it by linking the APP in a workspace.
> Adding RUS Profile Form

- CHANGELOG.md
- react/rules/POL.js
- react/rules/SGP.js
Add country rules for Poland (POL) and Singapore(SGP)
> Add country rules for Poland and Singapore

- CHANGELOG.md
- react/rules/POL.js
- react/rules/SGP.js
Add country rules for Poland (POL) and Singapore(SGP)
> add POL and SGP rules

- CHANGELOG.md
- react/rules/IND.js
This PR is the same as https://github.com/vtex/profile-form/pull/145 but for the master branch.
> Fix birthdate mask to save this field properly

- CHANGELOG.md
- react/rules/ZAF.js
Add South Africa country rules
> Add South Africa country rules

- CHANGELOG.md
- react/rules/AUS.js
- react/rules/CZE.js
- react/rules/IDN.js
- react/rules/NZL.js
- react/rules/SVK.js
Add Australia ('AUS'), Czech Republic ('CZE'), Indonesia ('IDN'), New Zealand ('NZL') and Slovakia ('SVK') country rules. Tracked by tasks [LOC-8769](https://vtex-dev.atlassian.net/browse/LOC-8769), [LOC-8800](https://vtex-dev.atlassian.net/browse/LOC-8800) and [LOC-8768](https://vtex-dev.atlassian.net/browse/LOC-8768).
> Add AUS, CZE, IDN, NZL and SVK country rules

- CHANGELOG.md
- react/rules/DEU.js
Added DEU birthDate mask. Tracked by task [LOC-8924](https://vtex-dev.atlassian.net/browse/LOC-8924).
> Add DEU birthDate mask

- CHANGELOG.md
- messages/ro.json
Fix Romanian translation. It replaces the https://github.com/vtex/profile-form/pull/161 PR.
> fix romanian translation

- CHANGELOG.md
- package.json
- react/package.json
- react/yarn.lock
- yarn.lock
> Jira: https://vtex-dev.atlassian.net/browse/LOC-8980
Update [@vtex/phone](https://github.com/vtex/front.phone) dependency
This project was using an old version of this lib. [This new version added a fix for FRA regarding phone numbers formatting](https://github.com/vtex/front.phone/pull/59).
At **My-account > profile**, try adding a mobile number, something that starts with a 6 or 7 (e.g. `700555900`)
[Before](http://t24.myvtex.com/account#/profile) vs [After](http://mobilenumber--t24.myvtex.com/account#/profile)
The problem was that [@vtex/phone](https://github.com/vtex/front.phone) was adding trailing zeros to the phone number.
> [Chore] Update vtex.phone

- CHANGELOG.md
- messages/en.json
> Fix English translation

- CHANGELOG.md
- package.json
This PR removes the `private` flag on the package.json
This change enables de publish of this package to NPM
> chore: :rocket: Remove private flag from package.json

- CHANGELOG.md
- react/rules/HUN.js
Add Hungary country rules to remove mandatory document. Tracked in task [LOC-12415](https://vtex-dev.atlassian.net/browse/LOC-12415).
https://sheilavtex--eternalhu.myvtex.com/account#/profile
[LOC-12415]: https://vtex-dev.atlassian.net/browse/LOC-12415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add Hungary country rules

- CHANGELOG.md
- react/rules/CRI.js
Tracked in task [LOC-12413](https://vtex-dev.atlassian.net/browse/LOC-12413).
[LOC-12413]: https://vtex-dev.atlassian.net/browse/LOC-12413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Show and require the ID field for Costa Rica as it is a government requirement

- CHANGELOG.md
- react/rules/HUN.js
Add Hungarian date mask to birth date
https://vtex-dev.atlassian.net/browse/OMS-5729
https://birthdate--probeautyhu.myvtex.com/account#/profile/edit
> Hungarian date mask

- CHANGELOG.md
- react/rules/AUT.js
Add Austria country rules. Tracked in task [LOC-14885](https://vtex-dev.atlassian.net/browse/LOC-14885).
[LOC-14885]: https://vtex-dev.atlassian.net/browse/LOC-14885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add Austria country rules

- CHANGELOG.md
- react/rules/AUT.js
Add Austria country rules. Tracked in task [LOC-14885](https://vtex-dev.atlassian.net/browse/LOC-14885).
[LOC-14885]: https://vtex-dev.atlassian.net/browse/LOC-14885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add  Austria country rules
